[hybris-boot] fix make target error introduced in Android 10
Adding targets to .PHONY is needed starting with Android 10
otherwise make fails with errors such as:

error: writing to readonly directory: "droidmedia"

Signed-off-by: Simonas Leleiva <simonas.leleiva@jolla.com>