[hybris-boot] etc/init/hybris_extras.rc is used only for Android 7 and greater
Presence of this file for older Android versions breaks package build:

For example for hammerhead (CyanogenMod 11.0 / Android 4.4):
$ rpm/dhd/helpers/build_packages.sh

'[' 4 -ge 7 ']'
echo ''
'[' -f ./out/target/product/hammerhead/system/etc/init/hybris_extras.rc ']'
cp -a ./out/target/product/hammerhead/system/etc/init/hybris_extras.rc /media/data/port/android/installroot/usr/libexec/droid-hybris/system/etc/init/
cp: cannot create regular file `/media/data/port/android/installroot/usr/libexec/droid-hybris/system/etc/init/': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.SrHvD1 (%install)